import { simulationEngineOrchestrator } from '../simulation/engine/index.js';
import { resultCollector } from '../results/collector/index.js';
import { aiResearchEngine, aiEngineOrchestrator } from '../ai/engine/index.js';
import { experimentRepository } from '../repositories/experimentRepository.js';
import { workspaceManager } from '../workspace/manager/index.js';
import { LoggerService } from '../logging/logger.js';
import { WorkflowContext } from './WorkflowContext.js';
import { workflowHistory } from './WorkflowHistory.js';
import { workflowPersistence } from './WorkflowPersistence.js';
import { workflowScheduler } from './WorkflowScheduler.js';
import { IWorkflowHistoryEntry } from './types.js';

const logger = new LoggerService('WorkflowRunner');

export class WorkflowRunner {
  /**
   * Executes or advances a workflow context through its lifecycle stages.
   */
  public async executeCycle(context: WorkflowContext): Promise<void> {
    if (context.isPaused) {
      logger.info(`Workflow ${context.workflowId} is paused. Skipping execution cycle.`);
      context.transitionTo('Waiting', 'Workflow is paused by user');
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));
      return;
    }

    if (context.stateTracker.isTerminal()) {
      logger.info(`Workflow ${context.workflowId} is in terminal state: ${context.state}.`);
      return;
    }

    try {
      // 1. Preparation Stage
      context.iteration += 1;
      const experimentId = `exp-${context.workflowId}-${context.iteration}`;
      const runId = `run-${context.workflowId}-${context.iteration}`;

      context.currentExperimentId = experimentId;
      context.currentRunId = runId;

      logger.info(`[Workflow ${context.workflowId}] Starting Iteration ${context.iteration} (Exp: ${experimentId})`);
      context.transitionTo('Preparing', `Initializing iteration ${context.iteration}`);
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));

      // Create experiment record in database repository
      const now = new Date().toISOString();
      experimentRepository.create({
        id: experimentId,
        projectId: context.projectId,
        title: `${context.goal.name} - Iteration ${context.iteration}`,
        description: `Automated run iteration ${context.iteration} generated by AI Research Engine.`,
        pluginId: context.pluginId,
        status: 'Ready',
        version: context.iteration,
        parameters: Object.entries(context.currentParameters).map(([k, v]) => ({
          key: k,
          name: k,
          value: v,
          unit: '',
        })),
        notes: [],
        attachments: [],
        tags: ['autonomous-workflow', context.goal.name],
        createdAt: now,
        updatedAt: now,
        createdBy: 'AI Research Workflow Engine',
      });

      // Create isolated workspace
      await workspaceManager.createWorkspace(experimentId, runId);

      // 2. Ready Stage
      context.transitionTo('Ready', 'Parameter set and workspace prepared');
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));

      // 3. Execution Stage (Call Simulation Engine)
      context.transitionTo('Running', 'Submitting simulation request to Simulation Engine');
      experimentRepository.update(experimentId, { status: 'Running' });
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));

      let simulationJob;
      try {
        simulationJob = await simulationEngineOrchestrator.submitAndExecute({
          experimentId,
          parameters: context.currentParameters as any,
          solverPluginId: context.pluginId,
          priority: 5,
        });
      } catch (simErr: any) {
        logger.warn(`Simulation execution error on workflow ${context.workflowId}: ${simErr.message}`);
        await this.handleExecutionFailure(context, simErr.message);
        return;
      }

      // Reset retry count on successful submission
      context.retryCount = 0;

      // 4. Parsing Stage (Collect & Parse Simulation Results)
      context.transitionTo('Parsing', 'Collecting and parsing simulation outputs');
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));

      const result = await resultCollector.collectFromWorkspace(
        experimentId,
        runId,
        context.simulator,
        context.pluginId
      );

      context.lastResult = result;

      // 5. Analyzing Stage (Call AI Research Engine)
      context.transitionTo('Analyzing', 'AI evaluating simulation result against research goal');
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));

      const nextRequest = await aiResearchEngine.processSimulationResult(
        context.goal,
        result,
        context.currentParameters,
        false
      );

      context.lastNextRequest = nextRequest;
      const historyEntry: IWorkflowHistoryEntry = {
        id: `hist-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
        workflowId: context.workflowId,
        experimentId,
        runId,
        iteration: context.iteration,
        state: context.state,
        parameters: { ...context.currentParameters },
        result,
        nextRequest,
        timestamp: new Date().toISOString(),
        notes: nextRequest.optimizationReason,
      };

      workflowHistory.addEntry(context.workflowId, historyEntry);

      // 6. Optimizing Stage & Stopping Condition Decision
      context.transitionTo('Optimizing', 'Determining next steps and checking stopping conditions');

      const { stoppingDecision } = nextRequest;

      if (stoppingDecision.shouldStop) {
        logger.info(
          `[Workflow ${context.workflowId}] Stopping condition triggered: ${stoppingDecision.reason}`
        );

        if (stoppingDecision.reason === 'Goal Achieved') {
          context.transitionTo('Completed', 'Target research goal successfully achieved!');
          // Generate Final Scientific Report
          try {
            const report = await aiEngineOrchestrator.generateScientificReport({
              experiment: {
                id: experimentId,
                name: context.goal.name,
                results: result,
              },
            });
            context.finalReport = report;
          } catch (repErr: any) {
            logger.warn(`Failed to generate final report for workflow ${context.workflowId}: ${repErr.message}`);
          }
        } else if (stoppingDecision.reason === 'User Stop') {
          context.transitionTo('Cancelled', 'Workflow stopped by user request');
        } else {
          context.transitionTo('Completed', `Workflow halted: ${stoppingDecision.reason}`);
        }

        workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));
        return;
      }

      // Goal Not Reached -> Update Parameters & Schedule Next Run
      context.currentParameters = { ...nextRequest.updatedParameters };
      context.transitionTo('SchedulingNextRun', 'Scheduling next optimization iteration');
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));

      // Auto-schedule next iteration (100ms delay to unblock call stack)
      workflowScheduler.scheduleNextRun(context.workflowId, 100, async () => {
        await this.executeCycle(context);
      });
    } catch (err: any) {
      logger.error(`Workflow ${context.workflowId} execution error:`, { error: err.message });
      await this.handleExecutionFailure(context, err.message);
    }
  }

  /**
   * Failure recovery logic for simulation errors, license locks, or plugin issues.
   */
  private async handleExecutionFailure(context: WorkflowContext, errorMessage: string): Promise<void> {
    context.retryCount += 1;
    const isLicenseError = errorMessage.toLowerCase().includes('license') || errorMessage.toLowerCase().includes('flexlm');

    if (isLicenseError) {
      logger.warn(`License error detected for workflow ${context.workflowId}. Retrying in 5000ms...`);
      context.transitionTo('Waiting', `License error encountered. Retrying (${context.retryCount}/${context.maxRetries})`);
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));

      workflowScheduler.scheduleNextRun(context.workflowId, 5000, async () => {
        await this.executeCycle(context);
      });
      return;
    }

    if (context.retryCount <= context.maxRetries) {
      logger.warn(
        `Retrying workflow ${context.workflowId} (Attempt ${context.retryCount}/${context.maxRetries}) due to error: ${errorMessage}`
      );
      context.transitionTo('Preparing', `Retrying execution due to error: ${errorMessage}`);
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));

      workflowScheduler.scheduleNextRun(context.workflowId, 1000, async () => {
        await this.executeCycle(context);
      });
    } else {
      logger.error(`Workflow ${context.workflowId} exceeded maximum retries (${context.maxRetries}). Transitioning to Failed.`);
      context.transitionTo('Failed', `Exceeded retry limit: ${errorMessage}`);
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));
    }
  }

  /**
   * Recovers a workflow that was interrupted during a server restart or crash.
   */
  public async recoverAndResumeWorkflow(context: WorkflowContext): Promise<void> {
    logger.info(`Recovering workflow ${context.workflowId} from state [${context.state}]`);

    // Clean up temporary files or workspaces if corrupted
    if (context.currentExperimentId && context.currentRunId) {
      try {
        workspaceManager.cleanupTemp(context.currentExperimentId, context.currentRunId);
      } catch {
        // Ignore workspace cleanup error during recovery
      }
    }

    if (context.state === 'Running' || context.state === 'Preparing' || context.state === 'Ready' || context.state === 'SchedulingNextRun' || context.state === 'Waiting') {
      context.transitionTo('Preparing', 'Automatically resumed following server crash/restart recovery');
      workflowPersistence.saveWorkflow(context, workflowHistory.getHistory(context.workflowId));
      await this.executeCycle(context);
    } else {
      logger.info(`Workflow ${context.workflowId} in state [${context.state}] does not require active resumption.`);
    }
  }
}

export const workflowRunner = new WorkflowRunner();
